FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY Domain/Eventide.AuthService.Domain.csproj Domain/
COPY Application/Eventide.AuthService.Application.csproj Application/
COPY Infrastructure/Eventide.AuthService.Infrastructure.csproj Infrastructure/
COPY WebAPI/Eventide.AuthService.WebAPI.csproj WebAPI/
COPY Contracts/Eventide.AuthService.Contracts.csproj Contracts/
RUN dotnet restore WebAPI/Eventide.AuthService.WebAPI.csproj

COPY . .

RUN dotnet publish WebAPI/Eventide.AuthService.WebAPI.csproj -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app .

ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080

ENTRYPOINT ["dotnet", "Eventide.AuthService.WebAPI.dll"]